<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>likec4</string>
    <key>scopeName</key>
    <string>source.likec4</string>
    <key>fileTypes</key>
    <array>
      <string>likec4</string>
      <string>like-c4</string>
      <string>c4</string>
    </array>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#comments</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#link-or-icon</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#string</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#relationship</string>
      </dict>
      <dict>
        <key>name</key>
        <string>keyword.control.likec4</string>
        <key>match</key>
        <string>\b(specification|model|views)\b</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(tag|kind)\s+is(\s+not)?\b</string>
        <key>name</key>
        <string>keyword.control.likec4</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(true|false)\b</string>
        <key>name</key>
        <string>constant.language.likec4</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(element|tag|relationship)\s+([^\s]+)\b</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.likec4</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.enum.likec4</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(rank)\s+(same|source|sink|min|max)\b</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.likec4</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.enum.likec4</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>match</key>
        <string>#[a-fA-F0-9]{3,8}</string>
        <key>name</key>
        <string>constant.other.color.likec4</string>
      </dict>
      <dict>
        <key>match</key>
        <string>#[a-zA-Z0-9]+</string>
        <key>name</key>
        <string>entity.name.type.enum.likec4</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(shape|head|tail|line|border|variant|size|padding|textSize|iconColor|iconPosition|iconSize):?\s+([-\w]+)\b</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>variable.other.property.likec4</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.enum.likec4</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>entity.name.variable.likec4</string>
        <key>match</key>
        <string>\b\.(\*|_){1,2}(?!\S)</string>
      </dict>
      <dict>
        <key>name</key>
        <string>entity.name.type.enum.likec4</string>
        <key>match</key>
        <string>\b(TopBottom|LeftRight|BottomTop|RightLeft|xsmall|xs|small|sm|medium|md|large|lg|xl|xlarge|diagram|sequence)\b</string>
      </dict>
      <dict>
        <key>name</key>
        <string>variable.other.property.likec4</string>
        <key>match</key>
        <string>\b(title|color|description|technology|navigateTo|notation|multiple|size|padding|textSize|opacity|variant|iconColor|iconPosition|iconSize)\b</string>
      </dict>
      <dict>
        <key>name</key>
        <string>keyword.control.likec4</string>
        <key>match</key>
        <string>\belement(\.(kind|tag)?)?\b</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#shapes</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#colors</string>
      </dict>
      <dict>
        <key>name</key>
        <string>keyword.control.likec4</string>
        <key>match</key>
        <string>\b(and|as|autoLayout|border|color|crow|dashed|description|deployment|deploymentNode|diamond|dot|dotted|dynamic|from|global|group|element|exclude|extend|extends|head|icon|iconColor|iconPosition|iconSize|icons|import|include|instance(Of)?|it|kind|line|likec4lib|link|metadata|model|navigateTo|node|none|not|normal|odiamond|odot|of|onormal|opacity|open|or|of|parallel|par|predicateGroup|predicate|rank|relationship|shape|solid|specification|styleGroup|style|tag|tail|technology|this|title|vee|view|views|where|source|target|with)\b</string>
      </dict>
      <dict>
        <key>name</key>
        <string>keyword.symbol.likec4</string>
        <key>match</key>
        <string>\{|\}|\(|\)|\:|\,|\;|\!|\=+</string>
      </dict>
      <dict>
        <key>name</key>
        <string>entity.name.function.likec4</string>
        <key>match</key>
        <string>\b(rgba|rgb)</string>
      </dict>
      <dict>
        <key>name</key>
        <string>constant.numeric.likec4</string>
        <key>match</key>
        <string>\b\d+(\.\d+|%)?</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>link-or-icon</key>
      <dict>
        <key>match</key>
        <string>\b(link|icon):?\s+([^\s]+)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>variable.other.property.likec4</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>string.quoted.single.likec4</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>none|(aws|azure|bootstrap|gcp|tech):([-\w]+)</string>
                <key>name</key>
                <string>entity.name.type.enum.likec4</string>
              </dict>
            </array>
          </dict>
        </dict>
      </dict>
      <key>relationship</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(-\[)([^\]]*)(\]-&gt;)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.likec4</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.likec4</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.likec4</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>name</key>
            <string>storage.type.function.likec4</string>
            <key>begin</key>
            <string>(-\[)</string>
            <key>end</key>
            <string>(\]-&gt;)</string>
          </dict>
          <dict>
            <key>name</key>
            <string>storage.type.function.likec4</string>
            <key>match</key>
            <string>(&lt;-&gt;|&lt;-|-&gt;)</string>
          </dict>
        </array>
      </dict>
      <key>comments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>comment.block.likec4</string>
            <key>begin</key>
            <string>/\*</string>
            <key>end</key>
            <string>\*/</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>//</string>
            <key>end</key>
            <string>(?=$)</string>
            <key>name</key>
            <string>comment.line.likec4</string>
          </dict>
        </array>
      </dict>
      <key>string</key>
      <dict>
        <key>name</key>
        <string>string.quoted.likec4</string>
        <key>begin</key>
        <string>("|')</string>
        <key>end</key>
        <string>(\1)</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#string-character-escape</string>
          </dict>
        </array>
      </dict>
      <key>string-character-escape</key>
      <dict>
        <key>name</key>
        <string>constant.character.escape.likec4</string>
        <key>match</key>
        <string>\\(x[0-9A-Fa-f]{2}|u[0-9A-Fa-f]{4}|u\{[0-9A-Fa-f]+\}|[0-2][0-7]{0,2}|3[0-6][0-7]?|37[0-7]?|[4-7][0-7]?|.|$)</string>
      </dict>
      <key>shapes</key>
      <dict>
        <key>name</key>
        <string>keyword.control.likec4</string>
        <key>match</key>
        <string>\b(rectangle|component|person|browser|mobile|cylinder|storage|queue|bucket|document)\b</string>
      </dict>
      <key>colors</key>
      <dict>
        <key>name</key>
        <string>entity.name.type.enum.likec4</string>
        <key>match</key>
        <string>\b(amber|blue|gray|green|indigo|muted|primary|secondary|red|sky|slate|none)\b</string>
      </dict>
    </dict>
  </dict>
</plist>